### ISSUE TITLE
can you write an error log?

### ISSUE THREAD

**Issue by lanybass** [danaugrs/gokoban#1]
I run the game "window x64 prebuild" version on my win7 x64 pc unsuccessfuly
nothing showed, and the process flashed in the TaskList

**Comment by justinclift** [comment]
As a thought, if you launch the program from a command line shell (eg cmd.exe), does it show any kind of error message or similar after the process has flashed in the TaskList?

Asking because that's a fairly common way to see errors on Win 7 and similar, and it should be easy to try. :smile:

**Comment by danaugrs** [comment]
Error reporting was probably improved by https://github.com/danaugrs/gokoban/commit/2a90032b92511cbe1c5cbed3703bdb399c82ab80.
