### ISSUE TITLE
Found an unusual thin line

### ISSUE THREAD

**Issue by electricface** [danaugrs/gokoban#11]
![image](https://user-images.githubusercontent.com/3241440/54508954-c61ee380-4982-11e9-985e-5743e1a67ec9.png)

![image](https://user-images.githubusercontent.com/3241440/54509163-8efd0200-4983-11e9-8994-9ff0192aec07.png)

**Comment by danaugrs** [comment]
What OS are you using?

**Comment by electricface** [comment]
linux， xorg

**Comment by danaugrs** [comment]
Thanks! Fixed in https://github.com/danaugrs/gokoban/commit/2a90032b92511cbe1c5cbed3703bdb399c82ab80.
