### ISSUE TITLE
Window is not closing properly

### ISSUE THREAD

**Issue by bmdelacruz** [danaugrs/gokoban#12]
The window is not closing properly when the game is closed via quit button. `g.win.Destroy()` must be called after the render loop.

https://github.com/danaugrs/gokoban/blob/8354b7514160bc831895d7c70c055c043b15c8e7/main.go#L1370-L1378

**Comment by danaugrs** [comment]
Thanks! Fixed in https://github.com/danaugrs/gokoban/commit/2a90032b92511cbe1c5cbed3703bdb399c82ab80.
