### ISSUE TITLE
No Function `GetMaterial`

### ISSUE THREAD

**Issue by Nv7-GitHub** [danaugrs/gokoban#14]
When I tried installing from source, I got the error:
```
# github.com/danaugrs/gokoban
go/pkg/mod/github.com/danaugrs/gokoban@v0.0.0-20180818141602-8354b7514160/main.go:548:33: skybox.Graphic.Materials()[i].GetMaterial undefined (type graphic.GraphicMaterial has no field or method GetMaterial)
```
How can I fix this?

**Comment by aabbtree77** [comment]
I had the same error on Ubuntu 20.04, March 17, 2021. The following worked for me:

1. ```cd $GOPATH/src/github.com/danaugrs```

If it does not exist, create the whole precise path, make sure that your GOPATH is not empty.

2. ```git clone https://github.com/jtolio/gokoban.git --branch patch-1 --single-branch```

This will create gokoban inside danaugrs. This particular branch by jtolio fixes the problem by replacing the line 548 in main.go

```sbmat := skybox.Materials()[i].GetMaterial().(*material.Standard)```

with 

```sbmat := skybox.Materials()[i].IMaterial().(*material.Standard)```

3. ```cd gokoban```
4. ```go mod init```
5. ```go mod tidy```
6. ```go mod vendor```
7. ```go build```
8. ./gokoban

**Comment by Nv7-GitHub** [comment]
Yes, I made a fork and did this

**Comment by danaugrs** [comment]
Thanks! Fixed in https://github.com/danaugrs/gokoban/commit/2a90032b92511cbe1c5cbed3703bdb399c82ab80.
