### ISSUE TITLE
cannot find module providing package github.com/g3n/engine/camera/control

### ISSUE THREAD

**Issue by meusingit** [danaugrs/gokoban#15]
attaching the screenshot:
![image](https://user-images.githubusercontent.com/45351138/151667427-6b2e2e94-5561-4811-b115-9fbfa788d352.png)

I checked for that package across your repo. Would you please let me know how to fix this?

**Comment by danaugrs** [comment]
Thanks! Fixed in https://github.com/danaugrs/gokoban/commit/2a90032b92511cbe1c5cbed3703bdb399c82ab80.
