### ISSUE TITLE
Compile failure with recent g3n

### ISSUE THREAD

**Issue by justinclift** [danaugrs/gokoban#2]
Just tried compiling this on CentOS 7 x64, with Go 1.9.2.

```
$ go get -u github.com/danaugrs/gokoban
# github.com/danaugrs/gokoban
go/src/github.com/danaugrs/gokoban/levelstyle.go:37:37: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:38:38: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:51:53: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:54:51: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:57:54: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:60:56: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/levelstyle.go:63:56: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/main.go:447:10: listener.SetDirectionv undefined (type *audio.Listener has no field or method SetDirectionv)
go/src/github.com/danaugrs/gokoban/main.go:623:55: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/main.go:653:56: too many arguments in call to math32.NewColor
        have (number, number, number)
        want (string)
go/src/github.com/danaugrs/gokoban/main.go:653:56: too many errors
```

Not sure what's up with the `math32.NewColor` error, but the `listener.SetDirectionv` just needed the method renamed to `SetDirectionVec` like in this:

&nbsp; &nbsp; https://github.com/g3n/engine/commit/443c5907c0fbee1d8dfca984515f71acd4bbd816

It seems like g3n api changes are stopping things from working.  If you're still interested in keeping this working, maybe vendoring the g3n repo here from before the api changes would work.  Guessing so, but not 100% sure. :smile:

**Comment by justinclift** [comment]
Looked into this a bit more.  Rewinding the local g3n/engine repo to commit [405cf4ea33b98dea4f2a5214544a8f6fd23c414c](https://github.com/g3n/engine/commit/405cf4ea33b98dea4f2a5214544a8f6fd23c414c) lets gokoban compile ok.

The application still hangs, likely trying to play .ogg audio, but that's seems to be a current incompatibility with CentOS 7 and g3n in general.  Unlikely to be gokoban's fault. :smile:

**Comment by justinclift** [comment]
Minor update.  Yep, the hang was a problem with g3n/engine, fixed today.

**Comment by justinclift** [comment]
Taking a more indepth look at this - easing myself back into Go coding after several months off - most of the errors seem fairly straightforward to update for.

Doing things in a branch here, if that's useful:

&nbsp; &nbsp; https://github.com/justinclift/gokoban/tree/engine_api_update_v1

Only 4 errors to go now.  Probably take a look at them tomorrow, as it's getting late now (sleep needed). :smile:

**Comment by danaugrs** [comment]
I've updated the code to match the latest G3N API and also vendored G3N as suggested :wink:

**Comment by justinclift** [comment]
Thanks @danaugrs, that's awesome.  I'll nuke my branch then, as I was struggling. :smile:

**Comment by justinclift** [comment]
Tried it now, and yep it all works.  Audio now plays too thanks to the fixed g3n/engine, and things look good.  Excellent. :smile:
