### ISSUE TITLE
Will not run unless cd to source directory

### ISSUE THREAD

**Issue by grkuntzmd** [danaugrs/gokoban#3]
When building from source (`go get -u github.com/danaugrs/gokoban`) the game installs in $GOPATH/bin, but it will not run unless you first change directory to `$GOPATH/src/github.com/danaugrs/gokoban`.

It gives the following error:
```
Gokoban:Error loading texture: open img/floor.png: no such file or directory
```

You might need to use [go-bindata](https://github.com/jteeuwen/go-bindata) to package the image inside the executable.

**Comment by quillaja** [comment]
Same

    23:17:14.311219:I:Gokoban:Initializing Gokoban
    23:17:14.679036:F:Gokoban:Error loading texture: open img/floor.png: no such file or directory
    panic: LOG FATAL

**Comment by quillaja** [comment]
seems to have worked =)
