### ISSUE TITLE
Level locks up if you move before the elevator animation ends

### ISSUE THREAD

**Issue by amyadzuki** [danaugrs/gokoban#6]
This level seems to have an easy solution if you could move while the elevator is moving.  I don't think you are supposed to be able to, but if you try then the level locks up until you reset.

```
........]
e--------
........]x
........]s
........]o
```

P.S. Omg, I love gokuban!!!  And so does my whole family!

**Comment by danaugrs** [comment]
Thanks! This bug was fixed here: https://github.com/danaugrs/gokoban/commit/617d7b989471747ed425bba0420b21ec710ab844.
